name: Flake 8
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  flake8:
    name: Flake 8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Flake 8
        uses: heitorpolidoro/flake8-with-PR-comments@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          flake_parameters: --max-line-length=127
